import { Photo } from '../model'

export const photos: Photo[] = [
  { src: 'images/148.jpg', author: 'MegabaitGamer' },
  { src: 'images/149.jpg', author: 'MegabaitGamer' },
  { src: 'images/150.png', author: 'MegabaitGamer' },
  { src: 'images/151.jpg', author: 'MegabaitGamer' },
  { src: 'images/152.jpg', author: 'MegabaitGamer' },
  { src: 'images/153.jpg', author: 'MegabaitGamer' },
  { src: 'images/154.png', author: 'MegabaitGamer' },
  { src: 'images/155.png', author: 'MegabaitGamer' },
  { src: 'images/156.png', author: 'MegabaitGamer' },
  { src: 'images/157.png', author: 'MegabaitGamer' },
  { src: 'images/158.png', author: 'MegabaitGamer' },
  { src: 'images/159.jpg', author: 'MegabaitGamer' },
  { src: 'images/160.jpg', author: 'MegabaitGamer' },
  { src: 'images/161.jpg', author: 'MegabaitGamer' },
  { src: 'images/162.jpg', author: 'MegabaitGamer' },
  { src: 'images/163.jpg', author: 'MegabaitGamer' },
  { src: 'images/164.jpg', author: 'MegabaitGamer' },
  { src: 'images/1.png', author: 'Лилия Самохвалова' },
  { src: 'images/2.png', author: 'Асеш Азария' },
  { src: 'images/3.jpg', author: 'Sheryl' },
  { src: 'images/4.jpg', author: 'Sheryl' },
  { src: 'images/5.jpg', author: 'beemi' },
  { src: 'images/6.png', author: 'Blue Лайм' },
  { src: 'images/7.png', author: 'YuriS' },
  { src: 'images/8.png', author: 'milkaFox' },
  { src: 'images/9.png', author: 'milkaFox' },
  { src: 'images/10.png', author: 'milkaFox' },
  { src: 'images/11.png', author: 'milkaFox' },
  { src: 'images/12.png', author: 'Александра Бондаренко' },
  { src: 'images/13.png', author: 'shi_nda' },
  { src: 'images/14.png', author: 'dev' },
  { src: 'images/15.jpg', author: 'neddia_' },
  { src: 'images/16.png', author: 'Villy' },
  { src: 'images/17.png', author: 'Ртуть' },
  { src: 'images/18.png', author: 'Shpilly Willy' },
  { src: 'images/19.png', author: 'Уилл Зеленьский' },
  { src: 'images/20.png', author: 'Анна Брак' },
  { src: 'images/21.jpg', author: 'Косат(ик)' },
  { src: 'images/22.png', author: 'Табуретка' },
  { src: 'images/23.png', author: 'Дарья Шакурова' },
  { src: 'images/24.png', author: 'BULKA' },
  { src: 'images/25.jpg', author: 'Давента Амелис' },
  { src: 'images/26.png', author: 'Royale High' },
  { src: 'images/27.jpg', author: 'Grelka' },
  { src: 'images/28.png', author: 'Yuki' },
  { src: 'images/29.png', author: 'Елена Огнева' },
  { src: 'images/30.png', author: 'Фраксус' },
  { src: 'images/31.png', author: 'Spider' },
  { src: 'images/32.jpg', author: 'Алина Кусь' },
  { src: 'images/33.png', author: 'Арина Пловецкая' },
  { src: 'images/34.png', author: 'Mitsura arts' },
  { src: 'images/35.png', author: 'TOVAHKIIN' },
  { src: 'images/36.jpg', author: 'Мария Вишнякова' },
  { src: 'images/37.png', author: 'Диана Чечельницкая' },
  { src: 'images/38.png', author: 'Екатерина Осипова' },
  { src: 'images/39.png', author: 'Лисица' },
  { src: 'images/40.png', author: 'Екатерина Усова' },
  { src: 'images/41.jpg', author: 'dozhdoley' },
  { src: 'images/42.jpg', author: 'dozhdoley' },
  { src: 'images/43.jpg', author: 'dozhdoley' },
  { src: 'images/44.jpg', author: 'dozhdoley' },
  { src: 'images/45.jpg', author: 'dozhdoley' },
  { src: 'images/46.png', author: 'dozhdoley' },
  { src: 'images/47.jpg', author: 'dozhdoley' },
  { src: 'images/48.jpg', author: 'dozhdoley' },
  { src: 'images/49.jpg', author: 'dozhdoley' },
  { src: 'images/50.jpg', author: 'dozhdoley' },
  { src: 'images/51.jpg', author: 'dozhdoley' },
  { src: 'images/52.jpg', author: 'dozhdoley' },
  { src: 'images/53.png', author: 'Арина Шишкина' },
  { src: 'images/54.png', author: 'Арина Шишкина' },
  { src: 'images/55.jpg', author: 'untexp' },
  { src: 'images/56.png', author: 'Леша Трахтенберг' },
  { src: 'images/57.png', author: 'Леша Трахтенберг' },
  { src: 'images/58.png', author: 'AirFly-pony' },
  { src: 'images/59.png', author: 'SonyaGer' },
  { src: 'images/60.png', author: 'Паша Евтеров' },
  { src: 'images/61.png', author: 'Аня Чистякова' },
  { src: 'images/62.jpg', author: 'Алена Миронова' },
  { src: 'images/63.png', author: 'Horned Unicorn' },
  { src: 'images/64.jpg', author: 'Reys The-Human' },
  { src: 'images/65.png', author: 'maslo' },
  { src: 'images/66.png', author: 'Эльмира Мастеренко' },
  { src: 'images/67.jpg', author: 'Роман Брабус' },
  { src: 'images/68.jpg', author: 'DOROTEA' },
  { src: 'images/69.jpg', author: 'Ева Сахаркова' },
  { src: 'images/70.png', author: 'Qwokken Sporghkjlp' },
  { src: 'images/71.png', author: 'Полина Астафурова' },
  { src: 'images/72.png', author: 'MWerryCult' },
  { src: 'images/73.jpg', author: 'Лима Скрайт' },
  { src: 'images/74.png', author: 'Cake Bats' },
  { src: 'images/75.png', author: 'ТУЧЕЛЬ' },
  { src: 'images/76.png', author: 'Ксения Бисько' },
  { src: 'images/77.png', author: 'Стас Придурок' },
  { src: 'images/78.png', author: 'mithriss' },
  { src: 'images/79.jpg', author: 'DARSON FAMILY' },
  { src: 'images/80.png', author: 'Hypocritical elf ' },
  { src: 'images/81.png', author: 'Arian Raif' },
  { src: 'images/82.png', author: 'Станислав Бойко' },
  { src: 'images/83.jpg', author: 'Xe-N-do~iLL 69' },
  { src: 'images/84.png', author: 'Аня Виноградова' },
  { src: 'images/85.png', author: 'Аня Виноградова' },
  { src: 'images/86.jpg', author: '' },
  { src: 'images/87.jpg', author: 'AstroNaut_F' },
  { src: 'images/88.png', author: 'BuvanyBu' },
  { src: 'images/89.jpg', author: 'Deo Marzipan' },
  { src: 'images/90.png', author: 'Мария Черепашкина' },
  { src: 'images/91.png', author: 'Диана Ибрагимова' },
  { src: 'images/92.png', author: 'OLGA BOD' },
  { src: 'images/93.png', author: 'Маха Хоронжук' },
  { src: 'images/94.jpg', author: 'Dann' },
  { src: 'images/95.jpg', author: 'Юлия Славкина' },
  { src: 'images/96.png', author: 'Вероника Крыскина' },
  { src: 'images/97.png', author: 'Ваня Чабрец' },
  { src: 'images/98.png', author: 'Тори' },
  { src: 'images/99.png', author: 'Вероника Птичка' },
  { src: 'images/100.png', author: 'Rubin O.B.' },
  { src: 'images/101.png', author: 'Люба Маркова' },
  { src: 'images/102.jpg', author: 'Маргарита Минькова' },
  { src: 'images/103.jpg', author: 'Татьяна Лисовиц' },
  { src: 'images/104.png', author: 'Персик' },
  { src: 'images/105.png', author: 'Oleg Gogol' },
  { src: 'images/106.png', author: 'copyofastrid' },
  { src: 'images/107.png', author: 'Юлия Химиченко' },
  { src: 'images/108.png', author: 'Полина Печкина' },
  { src: 'images/109.png', author: 'Im Not' },
  { src: 'images/110.png', author: 'SherCore' },
  { src: 'images/111.jpg', author: 'Паша Цезарь' },
  { src: 'images/112.png', author: 'Нина Вишнёвская' },
  { src: 'images/113.png', author: 'Нина Вишнёвская' },
  { src: 'images/114.png', author: 'Нина Вишнёвская' },
  { src: 'images/115.jpg', author: 'BurntSyrop' },
  { src: 'images/116.png', author: 'Christopher Ray' },
  { src: 'images/117.jpg', author: 'OREX' },
  { src: 'images/118.png', author: 'Remember the past and create the future' },
  { src: 'images/119.png', author: 'Ирина Гарькавец' },
  { src: 'images/120.jpg', author: 'шпротина' },
  { src: 'images/121.png', author: 'Ольга Коржичкина' },
  { src: 'images/122.png', author: 'Tweek' },
  { src: 'images/123.jpg', author: 'Александра Кострова' },
  { src: 'images/124.png', author: 'Ghosha' },
  { src: 'images/125.jpg', author: 'Юлия Гнездилова' },
  { src: 'images/126.jpg', author: 'DjkaSkan' },
  { src: 'images/127.png', author: 'Татьяна Богомол' },
  { src: 'images/128.png', author: 'h1kkage' },
  { src: 'images/129.jpg', author: 'xeniyy' },
  { src: 'images/130.png', author: 'coal_pit' },
  { src: 'images/131.jpg', author: 'Лена Заровная' },
  { src: 'images/132.png', author: 'Алина Ковалёва' },
  { src: 'images/133.png', author: 'Алина Ковалёва' },
  { src: 'images/134.jpg', author: 'Devi' },
  { src: 'images/135.jpg', author: 'Devi' },
  { src: 'images/136.jpg', author: 'Devi' },
  { src: 'images/137.jpg', author: 'Devi' },
  { src: 'images/138.jpg', author: 'Devi' },
  { src: 'images/139.jpg', author: 'Devi' },
  { src: 'images/140.jpg', author: 'Devi' },
  { src: 'images/141.jpg', author: 'Devi' },
  { src: 'images/142.jpg', author: 'Devi' },
  { src: 'images/143.jpg', author: 'Devi' },
  { src: 'images/144.jpg', author: 'Devi' },
  { src: 'images/145.jpg', author: 'Devi' },
  { src: 'images/146.png', author: 'Нает' },
  { src: 'images/147.jpg', author: 'dozhdoley' }
]
